### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by tanisharao511** [akshaytheau/Data-Science#5]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-47-8bf722dbf37e> in <module>
      7              ('clf', LogisticRegression()),
      8             ])
----> 9 naivebayes.fit(X_train,y_train)
     10 
     11 y_pred1=naivebayes.predict(X_test)

/opt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/sklearn/pipeline.py in fit(self, X, y, **fit_params)
    328         """
    329         fit_params_steps = self._check_fit_params(**fit_params)
--> 330         Xt = self._fit(X, y, **fit_params_steps)
    331         with _print_elapsed_time('Pipeline',
    332                                  self._log_message(len(self.steps) - 1)):

/opt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/sklearn/pipeline.py in _fit(self, X, y, **fit_params_steps)
    294                 message_clsname='Pipeline',
    295                 message=self._log_message(step_idx),
--> 296                 **fit_params_steps[name])
    297             # Replace the transformer of the step with the fitted
    298             # transformer. This is necessary when loading the transformer

/opt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/joblib/memory.py in __call__(self, *args, **kwargs)
    350 
    351     def __call__(self, *args, **kwargs):
--> 352         return self.func(*args, **kwargs)
    353 
    354     def call_and_shelve(self, *args, **kwargs):

/opt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/sklearn/pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
    738     with _print_elapsed_time(message_clsname, message):
    739         if hasattr(transformer, 'fit_transform'):
--> 740             res = transformer.fit_transform(X, y, **fit_params)
    741         else:
    742             res = transformer.fit(X, y, **fit_params).transform(X)

/opt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/sklearn/feature_extraction/text.py in fit_transform(self, raw_documents, y)
   1197 
   1198         vocabulary, X = self._count_vocab(raw_documents,
-> 1199                                           self.fixed_vocabulary_)
   1200 
   1201         if self.binary:

/opt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/sklearn/feature_extraction/text.py in _count_vocab(self, raw_documents, fixed_vocab)
   1127             vocabulary = dict(vocabulary)
   1128             if not vocabulary:
-> 1129                 raise ValueError("empty vocabulary; perhaps the documents only"
   1130                                  " contain stop words")
   1131 

ValueError: empty vocabulary; perhaps the documents only contain stop words

**Comment by akshaytheau** [comment]
Can you tell the file in which you are facing this issue ? Is it for Multi-class classification using machine learning ?
Seeing the error I think their is some data issue here.Please check whether the train data is proper. @tanisharao511

**Comment by akshaytheau** [comment]
Closing this for no response
